### ISSUE TITLE
Variable names for nested structs are ignored, but concatenations of field tags could be expected

### ISSUE THREAD

**Issue by bunyk** [go-simpler/env#52]
Given an example code like this:

```golang
package main

import (
	"fmt"

	"go-simpler.org/env"
)

func main() {
	var cfg Config
	if err := env.Load(&cfg, nil); err != nil {
		fmt.Println(err)
	}
	fmt.Printf("Exporting data from %s to %s\n", cfg.SourceDB.Name, cfg.DestinationDB.Name)
}

type Config struct {
	SourceDB      Database `env:"SOURCE_DB"`
	DestinationDB Database `env:"DESTINATION_DB"`
}

type Database struct {
	Name     string `env:"NAME"`
	User     string `env:"USER"`
	Password string `env:"PASSWORD"`
	Host     string `env:"HOST"`
	Port     string `env:"PORT"`
	SSLMode  string `env:"SSL_MODE"`
}
```

Running it by setting variables like intended by developers gives this:

```
$ NAME=test go run main.go 
Exporting data from test to test
```

Which is ok for some use cases, but I would want to have different databases for source , so I would want to run it like this:

```
$ SOURCE_DB_NAME=test2 DESTINATION_DB_NAME=test2 go run main.go 
Exporting data from  to 
```

But such variables are not parsed. Maybe such mode for nested vars could be added to options to not break backward compatibility? Or even no flag would be needed, since I imagine with current nesting scheme fields with embedded structs have no `env` tags, and basically have empty string name.

**Comment by bunyk** [comment]
I'm thinking to propose to our team migrating from spf13/viper to this, because of two advantages:
-  `default` tag looks way better than calls to `viper.SetDefault("key", "value")` (and we don't do that, we instead parse separate yaml  file :vomiting_face: in addition to parsing ENV, which leads to funny errors when there is a typo in env),
- having `required` will remove a lot of validations like `if db.Name == "" { return fmt.Errorf(...)`.

But in our nested structs we very often use some types multiple times (for message streams connections, etc) like in example above, and this behavior prevents us from trying this library in our project. 

If there are no objections of making this change here I could invest some time trying to write a PR that implements it.

**Comment by tmzane** [comment]
Hello, thank you for the detailed example 👍

While I personally prefer to use full variable names in struct tags because it is easier to read, like this:

```go
type Config struct {
	SourceDB struct {
		Name string `env:"SOURCE_DB_NAME"`
		User string `env:"SOURCE_DB_USER"`
	}
}
```

I can see why it would be helpful to be able to reuse some struct types with many fields, like in your example.

You're totally right, currently, nested struct tags are ignored, so we could implement it without breaking backward compatibility: do nothing if no tag is present and use it as a simple prefix for field tags if it is. So, given the following code:

```go
type Config struct {
	SourceDB struct {
		Name string `env:"NAME"`
		User string `env:"USER"`
	} `env:"SOURCE_DB_"`
}
```

We would look for `SOURCE_DB_NAME` and `SOURCE_DB_USER`.

Please note the `_` suffix in `SOURCE_DB_`: it's true that this is the most popular naming convention for environment variables, but some developers use KEBAB-NAMES or no separator at all, e.g. `DBNAME`. I've seen such examples in my career 😅. So, while it does not look pretty in struct definition, I would prefer if we cover all naming conventions without introducing some additional option, like `NameSeparator`. Would that work for you?

**Comment by bunyk** [comment]
Thanks for considering having this feature. I coded some raw implementation of this. It is missing documentation update, and probably something else, so I expect suggestions.

But about `_` suffixes, I would prefer having `NameSeparator` option. So without setting it it will work like you described (with default empty string value), giving `DBNAME`, or having to leave dangling underscores. Problem with writing `SOURCE_DB_` apart from not being pretty - knowing me & my teammates we would often forget to add underscores at the end, and then proceed to waste time debugging configuration & double checking deployment manifests & stuff. 

API would be more pleasant if we just could just call `env.Load(&cfg, &env.Options{NameSeparator: "_"})` once, and forget about "_" suffixes.

**Comment by bunyk** [comment]
I experimented with a change where `NameSeparator` is `_` by default, and there were two disadvantages of this choice (even though it is probably most common indeed).

First, if we make it `string`, check if it is default zero value `""` and replace that with `"_"` - we loose ability to configure empty string separator. No possibility for `DBNAME` anymore. So to be able to configure `""` separator, and still have default, this option would need to be a pointer to string, and that complicates complicates API:

```go
sep := "_"
env.Load(&cfg, &env.Options{NameSeparator: &sep})
```

Second, with default `"_"` value for separator, current use cases where struct fields have no env name break. So, something like
```
type Config struct {
	SourceDB struct {
		Name string `env:"SOURCE_DB_NAME"`
		User string `env:"SOURCE_DB_USER"`
	}
}
```
With all the default settings would want to parse `_SOURCE_DB_NAME` & `_SOURCE_DB_USER` from environment. :scream:  Because of the implicit `""` env on `SourceDB` field. Maybe there is way to work around this, but joining with empty string by default keeps backward compatibility.

Also, question about such option name: it probably should be `NameSep`, since there is already `SliceSep` option, right?

**Comment by bunyk** [comment]
Pushed a change with `NameSep` having `""` default value. 

But the worst thing of that change is that `Usage` now also needs options (to know how variable names are built), which changes its API.

**Comment by tmzane** [comment]
> First, if we make it `string`, check if it is default zero value `""` and replace that with `"_"` - we loose ability to configure empty string separator.

What if we made it a rune instead? That would allow us to distinguish zero value, `' '` and `'_'`. And it wouldn't be so awkward to use as a pointer to string 😅. We would sure lose the ability to configure multi character separators, but I'm not sure it is a real enough use case. Double underscore maybe? Please tell me what do you think about it.

> Second, with default "_" value for separator, current use cases where struct fields have no env name break.

Why not ignore `NameSep` completely if there is no `env` tag in the first place? That was my initial thought.

**Comment by tmzane** [comment]
Looks like your conclusion is correct, `""` is the most reasonable choice for the default value in these circumstances. Let's stick with it for now then.

**Comment by bunyk** [comment]
So, I slept thinking about `Usage`, and maybe it's possible to make it backward compatible using variadic arguments. Could try to update my PR with that later this weekend.

**Comment by tmzane** [comment]
> So, I slept thinking about `Usage`, and maybe it's possible to make it backward compatible using variadic arguments. Could try to update my PR with that later this weekend.

Unfortunately, it won't be truly backward compatible because code like this won't compile anymore:

```go
var f func(any, io.Writer) = env.Usage
```

I don't actually mind changing the signature of `Usage`, we're still behind v1.0.0, so no guaranties. Just thinking if there are better options.

**Comment by bunyk** [comment]
Maybe it could be done in two steps?

1. Quick and simple fix to the problem of reused types. The originally suggested `_` suffix in `SOURCE_DB_`. That would solve my use case without much changes, and without any breaking changes at all. 
2. Adding config as a breaking change, updating documentation and writing warning about required migration in release notes for next version. Users would need to change just 1 or 2 lines. Also, `Usage` implementation could additionally benefit by reporting about value of `SliceSep`.

**Comment by tmzane** [comment]
This is actually what I was thinking about :)

Let's just start with implementing nested struct prefixing and leave all the `Usage` related stuff for another PR. In the meantime we could try the new feature and maybe give the design for options a bit more thought.

Would you update the PR to revert the `Usage` changes for now? I could actually do it myself and then ping you for the review, if you don't have the time.

**Comment by tmzane** [comment]
Also, I've got another idea based on yours.

We could allow setting the `required` and `expand` options in nested struct tags and automatically apply them for all the child fields.

Then users would be able to do things like this:

```go
type Config struct {
	Foo string `env:"FOO"`
}

var cfg struct {
	Config `env:"APP_,required"`
}
```

Here, all environment variables declared in `Config` would be required and prefixed with `APP_`. Note that `Config` is embedded so you could still access `cfg.Foo` and others directly.

This is just my thought for now, but could be another PR later.

**Comment by bunyk** [comment]
It was a long way, but today our team finally merged first PR with ![image](https://github.com/go-simpler/env/assets/244042/097a581d-9ff7-4494-917c-b847a7be9618) and

![image](https://github.com/go-simpler/env/assets/244042/d8a93377-e29d-4604-8fa5-d1821a82e7b1)

Looks simpler

I'm still thinking that having additional options would be useful:
- `NameSep` to not have dangling `_`
- `ApplicationPrefix`, to prefix all the variables with the application name, helps to avoid name conflicts with kubernetes-embedded variables & similar stuff.

But that's breaking change, so maybe could wait until version 1. Is there a roadmap?

**Comment by tmzane** [comment]
> It was a long way, but today our team finally merged first PR with ![image](https://private-user-images.githubusercontent.com/244042/317283226-097a581d-9ff7-4494-917c-b847a7be9618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTI5NDgsIm5iZiI6MTcxMTYxMjY0OCwicGF0aCI6Ii8yNDQwNDIvMzE3MjgzMjI2LTA5N2E1ODFkLTlmZjctNDQ5NC05MTdjLWI4NDdhN2JlOTYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNzU3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGNkN2MxNDUwZDc0MzgwMWJlZmY3Y2E0OGQ3MDZlMzFiMTVmMmEzYzc2MTc4MjQ5MGU5ZWEwZDUyYTBhMDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ohDp7tnXj5rmT6wb2txqH6GyW7dwWmko8QHHlwO7fQA)

Nice! That's my favorite type of commits 😄

It's funny, because one of the reasons I made this library was the frustration of working with `viper`. I get its importance in the Go ecosystem, but it's still not my cup of tea.

> NameSep to not have dangling _

I opened #57 to address this issue. If you would like to work on this one, please feel free to. I experimented a bit with passing `NameSep`/`SliceSep` as struct tags but it did not look good, so let's just implemented it as discussed earlier.

> ApplicationPrefix, to prefix all the variables with the application name

You can actually do it already, please see my previous message. Would that work for you?

> But that's breaking change

As I said earlier, it would be no big deal if done carefully. We follow semver and do not guarantee no breaking changes until `v1.0.0`. I did a few breaking changes previously while experimenting with the API when there were fewer users. A release note announcing the change would be enough.
