### ISSUE TITLE
Module declares path

### ISSUE THREAD

**Issue by MrDimly** [go-simpler/env#65]
Hi

After command go-get - i got error

> go get github.com/go-simpler/env
> go: github.com/go-simpler/env@upgrade (v0.12.0) requires github.com/go-simpler/env@v0.12.0: parsing go.mod:
>         module declares its path as: go-simpler.org/env
>                 but was required as: github.com/go-simpler/env

It's uncomfortable
Thank you

**Comment by tmzane** [comment]
Hello,

Why would you go-get it as `github.com/go-simpler/env`?

The installation instructions in the readme clearly says `go get go-simpler.org/env`. Does it not work for you?

And please don't spam PRs.

**Comment by MrDimly** [comment]
> Why would you go-get it as `github.com/go-simpler/env`?

I think - because i'am newbees... very stupid
 
> And please don't spam PRs.

Sorry - it's was minute of leaks.

Thank you

**Comment by tmzane** [comment]
No worries, feel free to ask any questions.
